language: java
sudo: required

services:
 - docker

before_install:
 - docker-compose --version
 - cd application
 - cd components/sm-frontend
 - yarn install
 - yarn test
 - cd ../sm-backend
 - gradle test
 - cd ../../

script:
 - docker-compose up
 